name: Health check

on:
  schedule:
    - cron: '* 23 * * *'

jobs:
  health_check:
    runs-on: ubuntu-18.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v1.5
        with:
          url: https://frozen-spire-87459.herokuapp.com/health
          max-attempts: 3
          retry-delay: 10s
