name: Hello World!

on:
  push:
    braches:
      - master

jobs:
  hello_wordl_job:
    runs-on: ubuntu-18.04
    steps:
      - name: Say Hello
        run: |
          echo "Hello World!"
      - name: Now it is
        run: |
          date
      - name: Directory content
        run: |
          ls -l
