name: Testing stuff

on:
  push:
    branches:
      - main

jobs:
  a_test_job:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: contains skip
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        if: ${{ contains($COMMIT_MESSAGES, '#skip') }}
        run: echo skipping deployment
